// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4tNHjH0FrEbRwd1igEO090XaqZdb3a-8',
    appId: '1:782532393458:web:1add9ea9f22c2137abd36b',
    messagingSenderId: '782532393458',
    projectId: 'crusade-entrance-check',
    authDomain: 'crusade-entrance-check.firebaseapp.com',
    storageBucket: 'crusade-entrance-check.firebasestorage.app',
    measurementId: 'G-93P4EHKJ2V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDySSgf4TF37EYY1AQjCyBlsNnLfCJ5ah0',
    appId: '1:782532393458:android:06824e12a3b054eaabd36b',
    messagingSenderId: '782532393458',
    projectId: 'crusade-entrance-check',
    storageBucket: 'crusade-entrance-check.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2_PVWS5tX9kef47U4NCYih0lS60rrl3A',
    appId: '1:782532393458:ios:5f64ec1fe7a79df9abd36b',
    messagingSenderId: '782532393458',
    projectId: 'crusade-entrance-check',
    storageBucket: 'crusade-entrance-check.firebasestorage.app',
    iosBundleId: 'com.example.crusadeEntranceCheckApp',
  );
}
